### ISSUE TITLE
`globalThis.fetch is not a function` error on CircleCI orb

### ISSUE THREAD

**Issue by mtran999** [foo-software/lighthouse-check#83]
Hi, wasn't sure where to report this.

We've been using the lighthouse-check CircleCI orb and 4 days ago we started getting these errors with no changes on our end:
```
❌  Something went wrong while attempting to enqueue URLs for Lighthouse. See the error below.

 TypeError: Failed to fetch browser webSocket URL from http://127.0.0.1:4000/json/version: globalThis.fetch is not a function
    at getWSEndpoint (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:67:41)
    at getConnectionTransport (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:54:37)
    at _connectToBrowser (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:24:56)
    at PuppeteerNode.connect (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/puppeteer-core/lib/esm/puppeteer/common/Puppeteer.js:93:16)
    at PuppeteerNode.connect (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/puppeteer-core/lib/esm/puppeteer/node/PuppeteerNode.js:88:22)
    at gatherFn (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/lighthouse/core/gather/navigation-runner.js:283:35)
    at Function.gather (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/lighthouse/core/runner.js:210:31)
    at navigationGather (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/lighthouse/core/gather/navigation-runner.js:306:34)
    at async navigation (file:///usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/lighthouse/core/index.js:58:24)
    at async exports.default (/usr/lib/node_modules/@foo-software/lighthouse-check/node_modules/@foo-software/lighthouse-persist/dist/lighthousePersist.js:107:19)
```

We narrowed down the cause to be the latest version of the `foosoftware/lighthouse-check` docker image. The CircleCI orb executor is set to the latest tag so the errors started when the image was updated 4 days ago. Pinning the docker image to an older version in the CircleCI job fixed the issue.

Just thought I'd bring it up in case it's happening to anyone else.

**Comment by adamhenson** [comment]
Thanks for bringing this up @mtran999 and sorry for this experience. Yes, pinning the Docker image is the best bet. We're having issues with Node.js v18 and v20. I'm going to close this as I think pinning the image should be the favorable solution. FWIW the CircleCI Orb project is here https://github.com/foo-software/lighthouse-check-orb... but this is fine too.
